name: build

on: [push]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
        nim:
        - stable
        # - devel
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - id: install-nim
      if: runner.os != 'Windows'
      run: |
        curl -LsSf https://nim-lang.org/choosenim/init.sh > choosenim.sh
        sh choosenim.sh -y
        echo "PATH=${HOME}/.nimble/bin:${PATH}" >> "${GITHUB_ENV}"
        export PATH="${HOME}/.nimble/bin:${PATH}"
        choosenim ${{ matrix.nim }}
    - name: 'Install dependencies (Windows)'
      if: runner.os == 'Windows'
      shell: bash
      run: |
        curl.exe -LsSf https://github.com/dom96/choosenim/releases/download/v0.8.2/choosenim-0.8.2_windows_amd64.exe -o choosenim.exe
        echo "${{ github.workspace }}/dist/mingw64/bin" >> "${GITHUB_PATH}"
        echo "${HOME}/.nimble/bin" >> "${GITHUB_PATH}"
        echo n | ./choosenim.exe ${{ matrix.nim }}
    - name: Test
      shell: bash
      run: |
        nimble test || env
