name: build

on: [push]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
        nim:
        - stable
        # - devel
    steps:
    - uses: actions/checkout@v2
    - id: install-nim
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        curl -LsSf https://nim-lang.org/choosenim/init.sh > choosenim.sh
        sh choosenim.sh -y
        echo "PATH=/home/runner/.nimble/bin:$PATH" >> $GITHUB_ENV
        export PATH=/home/runner/.nimble/bin:$PATH
        choosenim ${{ matrix.nim }}
    - id: install-nim-windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        curl.exe -LsSf https://github.com/dom96/choosenim/releases/download/v0.8.2/choosenim-0.8.2_windows_amd64.exe -o choosenim.exe
        choosenim.exe
    - name: Test
      run: |
        nimble refresh
        nimble test
