name: tests

concurrency:
  group: tests
  cancel-in-progress: true

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - master

jobs:
  noskipci:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "not contains '[skip ci]'"

  tests:
    needs: noskipci
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - macOS-10.15
          - macOS-11
          - windows-2016
          - windows-2022
        test:
          - all
          - regression
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Test ${{matrix.os}}
      if: runner.os != 'Windows'
      run: |
        curl -LsSf https://nim-lang.org/choosenim/init.sh > choosenim.sh
        sh choosenim.sh -y
        echo "PATH=${HOME}/.nimble/bin:${PATH}" >> "${GITHUB_ENV}"
        export PATH="${HOME}/.nimble/bin:${PATH}"
        choosenim stable
        nimble test_${{matrix.test}}
        nimble docs
    - name: Test ${{matrix.os}}
      if: runner.os == 'Windows'
      shell: bash
      run: |
        curl.exe -LsSf https://github.com/dom96/choosenim/releases/download/v0.8.2/choosenim-0.8.2_windows_amd64.exe -o choosenim.exe
        echo n | ./choosenim.exe stable
        export PATH="${HOME}/.nimble/bin:${PATH}"
        echo y | nimble install
        tasklist
        nimble --nim:"${HOME}/.nimble/bin/nim.exe" test_${{matrix.test}}
        nimble docs

  tests-devel:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Test Nim Devel
      run: |
        curl -LsSf https://nim-lang.org/choosenim/init.sh > choosenim.sh
        sh choosenim.sh -y
        echo "PATH=${HOME}/.nimble/bin:${PATH}" >> "${GITHUB_ENV}"
        export PATH="${HOME}/.nimble/bin:${PATH}"
        choosenim devel
        nimble test_all
        nimble docs
